adaptive_version = "BU21"
dtypes = {
    "DataReport": {
        'LevelName': 'str',
        'AccountCode': 'str',
        'CostCentre': 'str',
        'Partner': 'str',
        'codeAcc': 'str',
        'intercoAccount': 'str',
        'FlowAccount': 'str',
        'AccountName': 'str',
        'D_SC': 'str',
        'D_AU': 'str',
        'Period_Level': 'str',
        'Period_Partner': 'str',
        'Scope': 'str',
        'Scope_T1': 'str'
        },
    "FC19": {
        'D_RU': 'str',
        'codeAcc': 'str',
        'Partner': 'str',
        'D_AU': 'str',
        'FlowAccount': 'str',
        'AccountName': 'str',
        'AccountCode': 'str',
        'CostCentre': 'str',
        'intercoAccount': 'str',
        },
    "F00": {},
    "SellDown_ConsoFlag": {
        'Level': 'str',
        'Level Type': 'str',
        'Country': 'str',
        'Company Code': 'str',
        'Account Code': 'str',
        'CostCentre': 'str',
        'Partner': 'str',
        'Amount': 'int64',
        'codeAcc': 'str',
        'intercoAccount': 'str',
        'platformAccount': 'str',
        'FlowAccount': 'str',
        'BSSourceAccount': 'str',
        'Currency': 'str',
        'Account Name': 'str'
        },
    "dim_company": {
        'Platform': 'str',
        'Country': 'str',
        'Company SIM': 'str',
        'Company SAP': 'str',
        'Company Name SAP': 'str',
        'Reporting Segment': 'str',
        'Consolidation Method': 'str',
        '% EBITDA CONTRIBUTION': 'str',
        '% NET OWNERSHIP': 'str'
        },
    "company_classif": {
        'SAP CODE': 'str',
        'Base/Growth': 'str',
        'Sell Down': 'str',
        'Sell Down EDPR Remaining Stake': 'str',
        'Opex Classification': 'str',
        'COD Reported/Expected': 'str',
        'CLUSTER': 'str',
        'Country': 'str',
        'TEI Type': 'str',
        'TEI SPV': 'str',
        'CLUSTER ENEOP': 'str',
        'Sold in BP18-22R': 'str',
        'Check COD': 'str',
        'vs BP': 'str',
        'Unnamed: 14': 'str',
        'Unnamed: 15': 'str'
        },
    "levels": {
        'Unnamed: 0': 'str',
        'Parent Level Short': 'str',
        'Parent Level Name': 'str',
        'Level ID': 'str',
        'Lavel Name': 'str',
        'Level Short Name': 'str',
        'Level isElimination': 'str',
        'Level isImportable': 'str',
        'Level hasChildren': 'str',
        'Level Currency': 'str',
        'Busbar_hub_reference': 'str',
        'Company': 'str',
        'Company_sub': 'str',
        'Country': 'str',
        'Park': 'str',
        'Level_type': 'str',
        'Platform_Cube': 'str',
        'Vento_Holding': 'str',
        'Parent Level Short.1': 'str',
        'Parent Level Name.1': 'str',
        'Parent 2 Level Short': 'str',
        'Parent 2 Level Name': 'str',
        'Parent 3 Level Short': 'str',
        'Parent 3 Level Name': 'str',
        'Parent 4 Level Short': 'str',
        'Parent 4 Level Name': 'str',
        'Parent 5 Level Short': 'str',
        'Parent 5 Level Name': 'str',
        'Parent 6 Level Short': 'str',
        'Parent 6 Level Name': 'str',
        'Parent 7 Level Short': 'str',
        'Parent 7 Level Name': 'str'
        },
    "extramappingsbu21": {
        'Parent Level Short': 'str',
        'Parent Level Name': 'str',
        'Level ID': 'str',
        'Lavel Name': 'str',
        'Level Short Name': 'str',
        'Level isElimination': 'str',
        'Level isImportable': 'str',
        'Level hasChildren': 'str',
        'Level Currency': 'str',
        'Busbar_hub_reference': 'str',
        'Company': 'str',
        'Company_sub': 'str',
        'Country': 'str',
        'Park': 'str',
        'Level_type': 'str',
        'Platform_Cube': 'str',
        'Vento_Holding': 'str',
        'Parent 2 Level Name': 'str',
        'Parent 3 Level Name': 'str',
        'Parent 4 Level Name': 'str',
        'Group Level': 'str',
        'Platform Level': 'str',
        'Country Level': 'str',
        'Country Special Level': 'str',
        'Company Level': 'str'},
    "extramappings": {
        'Company SIM': 'str',
        'Company SAP': 'str',
        'Company Name SAP': 'str',
        'Reporting Segment': 'str',
        'Consolidation Method': 'str',
        '% EBITDA CONTRIBUTION': 'str',
        '% NET OWNERSHIP': 'str',
        'Platform': 'str',
        'Country': 'str'}
}

